version: '3'

services:
  test:
    build: .
    command: bash -c "
        ruff check && \
        ruff linter && \
        pytest --cov=coco --cov=tests"

  testv:
    build: .
    command: bash -c "
        ruff check && \
        ruff linter && \
        pytest --cov=coco --cov=tests"
    volumes:
    -  .:/root/coco-tools

  bash:
    build: .
    command: bash

  bashv:
    build: .
    command: bash
    volumes:
    -  .:/root/coco-tools

