name: Build

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: set pythonpath
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          echo "PATH=${PATH}:${HOME}/.local/bin" >> $GITHUB_ENV
      - name: Install Requirements
        run: |
          pip3 install --user -r requirements.txt
          python3 setup.py install
      - name: Run tests
        run: |
          pycodestyle coco tests
          pytest --cov=.
